title: Wonjune's note
description: 
theme: just-the-docs

url: https://devsigner9920.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
