title: Wonjune's note
description: 
theme: just-the-docs

url: https://devsigner9920.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

favicon_ico: "/assets/images/favicon.ico"

collections:
  tests:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    tests:
      name: Tests
    tutorials:
      name: Tutorials